### Server configuration ###
server.port=8000

### Database configuration ###
spring.datasource.url=jdbc:postgresql://localhost:5432/editora
spring.datasource.username=postgres
spring.datasource.password=SENHA_BD
spring.jpa.hibernate.ddl-auto=update

### HikariCP Connection Pool Configuration ###
# HikariCP é o gerenciador de pool de conexões no SpringBoot(considerado um dos mais rápidos e eficientes do mercado).

# Número máximo de conexões (ativas + inativas) que o pool pode manter.
spring.datasource.hikari.maximum-pool-size=10

# Número mínimo de conexões inativas que o Hikari tenta manter no pool.
# (O padrão do Hikari é manter o mesmo valor do maximum-pool-size para melhor performance)
spring.datasource.hikari.minimum-idle=5

# Tempo máximo em milissegundos que a aplicação vai esperar por uma conexão do pool (Padrão: 30000ms / 30s)
spring.datasource.hikari.connection-timeout=20000

# Tempo máximo em milissegundos que uma conexão pode ficar inativa (idle) antes de ser fechada.
spring.datasource.hikari.idle-timeout=300000

# Tempo máximo de vida de uma conexão no pool (Padrão: 1800000ms / 30min).
# É boa prática manter um pouco menor que o timeout do banco de dados (PostgreSQL).
spring.datasource.hikari.max-lifetime=1200000

