### Context path #########
server.servlet.context-path=/secauth

#Exclude path to auto-restart
spring.devtools.restart.exclude=resources/**

#Config Gerais - Clientes de aplicativo
spring.security.oauth2.client.registration.cognito.clientId=m4jidj2og7di30l7i90n5r2fb
spring.security.oauth2.client.registration.cognito.client-secret=1k3scoo124bl7c37t2cg1sgqk21ucs20r7a3nseumff2b297hu2b
spring.security.oauth2.client.registration.cognito.scope=openid 
spring.security.oauth2.client.registration.cognito.redirect-uri=http://localhost:8080/secauth/login/oauth2/code/cognito
spring.security.oauth2.client.registration.cognito.client-name=SecAuth

#https://cognito-idp.{region}.amazonaws.com/{Pool Id}
spring.security.oauth2.client.provider.cognito.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_vzpAwrxdz
spring.security.oauth2.client.provider.cognito.user-name-attribute=cognito:username

#Config extra
app.cognito.logoutURL=https://secauth.auth.us-east-1.amazoncognito.com/logout
app.cognito.redirectURI=http://localhost:8080/secauth
