### Context path #########
server.servlet.context-path=/secauth

#Exclude path to auto-restart
spring.devtools.restart.exclude=resources/**

#Config Gerais - Clientes de aplicativo
spring.security.oauth2.client.registration.cognito.clientId=2l21hvrgbc3846i27eafh9t2jd
spring.security.oauth2.client.registration.cognito.client-secret=ocehofsn2clslbj1qosdmttsin8rt47alcb13hani6685rjr4g0
spring.security.oauth2.client.registration.cognito.scope=openid 
spring.security.oauth2.client.registration.cognito.redirect-uri=http://localhost:8080/secauth/login/oauth2/code/cognito
spring.security.oauth2.client.registration.cognito.client-name=SecAuth2

#https://cognito-idp.{region}.amazonaws.com/{Pool Id}
spring.security.oauth2.client.provider.cognito.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_5ywhiB1me
spring.security.oauth2.client.provider.cognito.user-name-attribute=cognito:username

#Config extra
app.cognito.logoutURL=https://secauth2.auth.us-east-1.amazoncognito.com/logout
app.cognito.redirectURI=http://localhost:8080/secauth
